# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# OH-MY-ZSH THEME
ZSH_THEME="powerlevel10k/powerlevel10k"

# PLUGINS
plugins=(git nvm)

# SOURCE OH-MY-ZSH main configuration.
source $ZSH/oh-my-zsh.sh

# ALIASES
alias zshconfig="code ~/.zshrc"

# ANDROID STUDIO
export ANDROID_HOME=~/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin

# FLUTTER
export FVM_HOME=$HOME/fvm
export PATH=$FVM_HOME/default/bin:$PATH
export CHROME_EXECUTABLE='/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'

# DOTNET
export DOTNET_ROOT="/opt/homebrew/opt/dotnet/libexec"
export DOTNET_CLI_TELEMETRY_OPTOUT="1"

# SOURCE POWERLEVEL10K THEME
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh